# Generated by Django 3.0.7 on 2024-03-04 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='gstin',
        ),
    ]
